### ISSUE TITLE
possible feature ? BMI on Graph 

### ISSUE THREAD

**Issue by sinedo** [wger-project/wger#462]
Although the BMI is not as good as other measurements it gives you a rough estimate where your weight should be located 
It would be cool to have a checkbox which enables the a transparent color of the bmi displayed in the background of the graph 

![Graph_with_BMI](https://user-images.githubusercontent.com/46466615/84596315-3a358900-ae5d-11ea-9c04-2be4cfb7e16f.png)

**Comment by rolandgeider** [comment]
Yeah, this sounds useful

**Comment by Svn-Sp** [comment]
@rolandgeider I'm new to Github, but I'd like to try this one.

**Comment by rolandgeider** [comment]
Hi @Svn-Sp ! Sure, do you have a working development instance? I still haven't uploaded the new Docker images... 🙈 We can coordinate us in the gitter channel, or here if you want

**Comment by Svn-Sp** [comment]
Have installed wger for developement, but when I go to the weight overview page I just get the table but no graph...

**Comment by rolandgeider** [comment]
Strange, if you have entries there, it should show you something. Does the development server show 404 errors?

**Comment by Svn-Sp** [comment]
![screen](https://user-images.githubusercontent.com/69042800/89727340-04a7b900-da24-11ea-850b-d158c40486a0.jpg)
There are no 404's in the console...

**Comment by rolandgeider** [comment]
I'll take a look at master. I've been working on a different branch with mobile templates (which I'll hope I'll be able to merge soon) and there it's definitely working

**Comment by rolandgeider** [comment]
I've merged the branch into master and the weight overview is working (other things are ugly, but should still be functional). The CSS/JS libraries are downloaded with yarn now, the easiest thing is probably to use docker-compose, but you can download the dependencies yourself with ``yarn install``

**Comment by Svn-Sp** [comment]
Excuse me if this isn't the smartest question, but could you post the complete ```yarn install``` command?

**Comment by rolandgeider** [comment]
``yarn install`` is the whole command 😄. You call it from the source folder and it should download everything to wger/core/static/yarn/

![image](https://user-images.githubusercontent.com/2280729/90024783-924e0780-dcb5-11ea-988d-a462b064654f.png)


I really can't think of a reason why it wouldn't show anything

**Comment by Svn-Sp** [comment]
Still the same problem; No graph is showing and no 404's in the console.
I think ```yarn install``` did not work properly
![yarn install](https://user-images.githubusercontent.com/69042800/90262047-0f13e980-de4e-11ea-95aa-ef73652dcb7d.jpg)
<b>There is still no  /yarn folder in wger/core/static !</b>

**Comment by rolandgeider** [comment]
it's strange that yarn says there's a lock from another package manager, did you pull the latest stuff from master? What does ``git log -2`` say?

**Comment by Svn-Sp** [comment]
Output of ```git log -2```:
![log -2](https://user-images.githubusercontent.com/69042800/90309529-a5e1b400-dee9-11ea-9578-039e0ad7df99.jpg)

**Comment by Svn-Sp** [comment]
How should I implement this, I mean should I draw the lines in the svg or has d3 a function for this or what should I do?

**Comment by rolandgeider** [comment]
> Ok, so I don't really know how I did it, but now it runs! I am gonna start working on the feature now.
> Thank you for your patience!

😂😂 I feel you. When it suddenly starts (or stops) working and you don't know why...

**Comment by rolandgeider** [comment]
For the weight chart we use [metricsgraphics](https://github.com/metricsgraphics/metrics-graphics), you can look there if it is possible to draw on top of an existing chart. D3 is used in the background, perhaps it's possible to access that?

**Comment by Svn-Sp** [comment]
Have opened a PR...

**Comment by rolandgeider** [comment]
PR was merged, closing here
